export const ADD_PARKING = "ADD_PARKING";
export const DELETE_PARKING = "DELETE_PARKING";
export const PARKINGS_LOADING = "PARKINGS_LOADING";
export const EDIT_PARKING = "EDIT_PARKING";
export const GET_PARKINGS = "GET_PARKINGS";
export const FETCH_PARKINGS_FAILURE = "FETCH_PARKINGS_FAILURE";
